# Generated by Django 5.1.2 on 2024-11-06 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacao',
            old_name='nro_lacre',
            new_name='nro_lacre1_entrada',
        ),
        migrations.RenameField(
            model_name='operacao',
            old_name='nro_mdfe',
            new_name='nro_mdfe_entrada',
        ),
        migrations.RenameField(
            model_name='operacao',
            old_name='nro_notafiscal',
            new_name='nro_notafiscal_entrada',
        ),
        migrations.AddField(
            model_name='operacao',
            name='nro_lacre1_saida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nro_lacre2_entrada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nro_lacre2_saida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nro_mdfe_saida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nro_notafiscal_saida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='user_entrada',
            field=models.ForeignKey(db_column='id_usuario_entrada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_entrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacao',
            name='user_saida',
            field=models.ForeignKey(db_column='id_usuario_saida', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_saida', to=settings.AUTH_USER_MODEL),
        ),
    ]
