# Generated by Django 5.1.2 on 2024-11-06 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('motorista', '0001_initial'),
        ('operacao', '0002_rename_nro_lacre_operacao_nro_lacre1_entrada_and_more'),
        ('veiculo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='dta_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='dta_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='empresa_destino',
            field=models.ForeignKey(blank=True, db_column='id_empresa_destino', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_destino', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='empresa_origem',
            field=models.ForeignKey(blank=True, db_column='id_empresa_origem', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_origem', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='motorista',
            field=models.ForeignKey(blank=True, db_column='id_motorista', null=True, on_delete=django.db.models.deletion.PROTECT, to='motorista.motorista'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='placa',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='status',
            field=models.CharField(blank=True, default='Pendente', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='user_entrada',
            field=models.ForeignKey(blank=True, db_column='id_usuario_entrada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_entrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='user_saida',
            field=models.ForeignKey(blank=True, db_column='id_usuario_saida', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_saida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='veiculo',
            field=models.ForeignKey(blank=True, db_column='id_veiculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='veiculo.veiculo'),
        ),
    ]
