# Generated by Django 5.1.2 on 2024-10-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='tb_usuario',
        ),
    ]
