# Generated by Django 5.1.2 on 2024-10-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id_motorista', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=45, unique=True)),
                ('cnh', models.CharField(max_length=45, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=45, null=True)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
            ],
            options={
                'db_table': 'tb_motorista',
            },
        ),
    ]
