# Generated by Django 5.1.1 on 2024-10-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('motorista', '0001_initial'),
        ('veiculo', '0002_alter_veiculo_situacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id_operacao', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=45)),
                ('dta_saida', models.DateTimeField()),
                ('dta_entrada', models.DateTimeField()),
                ('status', models.CharField(max_length=45)),
                ('nro_mdfe', models.IntegerField(blank=True, null=True)),
                ('nro_notafiscal', models.IntegerField(blank=True, null=True)),
                ('nro_lacre', models.IntegerField()),
                ('empresa_destino', models.ForeignKey(db_column='id_empresa_destino', on_delete=django.db.models.deletion.PROTECT, related_name='empresa_destino', to='empresa.empresa')),
                ('empresa_origem', models.ForeignKey(db_column='id_empresa_origem', on_delete=django.db.models.deletion.PROTECT, related_name='empresa_origem', to='empresa.empresa')),
                ('motorista', models.ForeignKey(db_column='id_motorista', on_delete=django.db.models.deletion.PROTECT, to='motorista.motorista')),
                ('usu_cadentrada', models.ForeignKey(db_column='usu_cadentrada', on_delete=django.db.models.deletion.PROTECT, related_name='usuario_entrada', to=settings.AUTH_USER_MODEL)),
                ('usu_cadsaida', models.ForeignKey(db_column='usu_cadsaida', on_delete=django.db.models.deletion.PROTECT, related_name='usuario_saida', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(db_column='id_veiculo', on_delete=django.db.models.deletion.PROTECT, to='veiculo.veiculo')),
            ],
            options={
                'indexes': [models.Index(fields=['veiculo'], name='idx_operacao_veiculo'), models.Index(fields=['motorista'], name='idx_operacao_motorista'), models.Index(fields=['empresa_origem'], name='idx_operacao_origem'), models.Index(fields=['empresa_destino'], name='idx_operacao_destino'), models.Index(fields=['usu_cadsaida'], name='idx_operacao_saida'), models.Index(fields=['usu_cadentrada'], name='idx_operacao_entrada')],
            },
        ),
    ]
