# Generated by Django 5.1.2 on 2024-10-28 23:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confronto',
            fields=[
                ('id_confronto', models.AutoField(primary_key=True, serialize=False)),
                ('dta_confronto', models.DateField(default=datetime.datetime(2024, 10, 28, 20, 45, 39, 930292))),
                ('status', models.CharField(max_length=45)),
                ('comentario', models.TextField()),
                ('operacao', models.ForeignKey(db_column='id_operacao', on_delete=django.db.models.deletion.PROTECT, to='operacao.operacao')),
            ],
            options={
                'db_table': 'tb_confronto',
                'indexes': [models.Index(fields=['operacao'], name='idx_confronto_operacao')],
            },
        ),
    ]
