# Generated by Django 5.1.2 on 2024-10-29 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confronto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confronto',
            name='dta_confronto',
            field=models.DateField(default=datetime.datetime(2024, 10, 28, 21, 30, 3, 334507)),
        ),
    ]
