# Generated by Django 5.1.2 on 2024-10-20 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confronto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confronto',
            name='dta_confronto',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 14, 10, 58, 701386)),
        ),
    ]
