# Generated by Django 5.1.2 on 2024-10-20 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confronto', '0005_alter_confronto_dta_confronto'),
    ]

    operations = [
        migrations.AddField(
            model_name='confronto',
            name='comentario',
            field=models.TextField(default='nenhum comentário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confronto',
            name='dta_confronto',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 20, 54, 7, 758124)),
        ),
    ]
