# Generated by Django 5.1.2 on 2024-10-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('ano', models.IntegerField()),
                ('tipo_veiculo', models.CharField(max_length=45)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
            ],
            options={
                'db_table': 'tb_veiculo',
                'managed': True,
            },
        ),
    ]
