# Generated by Django 5.1.2 on 2024-10-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={},
        ),
    ]
