# Generated by Django 5.1.1 on 2024-10-10 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confronto',
            fields=[
                ('id_confronto', models.AutoField(primary_key=True, serialize=False)),
                ('dta_confronto', models.DateTimeField()),
                ('situacao', models.CharField(max_length=45)),
                ('justificativa', models.CharField(max_length=45)),
                ('observacao', models.CharField(blank=True, max_length=45, null=True)),
                ('operacao', models.ForeignKey(db_column='id_operacao', on_delete=django.db.models.deletion.CASCADE, to='operacao.operacao')),
                ('usu_confronto', models.ForeignKey(db_column='usu_confronto', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['operacao'], name='idx_confronto_operacao'), models.Index(fields=['usu_confronto'], name='idx_confronto_usuario')],
            },
        ),
    ]
